prefix = '>>'
[TOKENS]
bot = ''
idevision = ''
mystbin = ''

[DATABASE]
dsn = ''

# 50 = CRITICAL
# 40 = ERROR
# 30 = WARNING
# 20 = INFO
# 10 = DEBUG
[LOGGING]
webhook_url = ""
level = 20

[SNEKBOX] # optional
url = 'http://localhost:8060' # default url
